<div id="knockout-tutorials" class="knockout-tutorials" data-bind="scope:'kocomponent'">
    <p>The name and age is <span data-bind="text: personName() + ' ' +  personAge()"></span></p>
    <p>The name is <span data-bind="text: personName"></span></p>
    <p>The age is <span data-bind="text: personAge()"></span></p>
</div>
<script type="text/x-magento-init">
	{
		"#knockout-tutorials":{
			"Magento_Ui/js/core/app":{
				"components":{
					"kocomponent":{
						"component":"Magento_KnockoutJs/js/component"
					}
				}
			}
		}
	}
</script>
